####### BUSQUEDA DE REF Y ALT EN EL ARCHIVO DE INTSAMPLE Y EXTSAMPLE DE SNPs #########


#Intsamples
grep -i "rPodLil1.1_ChrZ	1004651" intSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_ChrZ	1004651	.	C	G
grep -i "rPodLil1.1_Chr17	838005" intSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr17	838005	.	T	C
grep -i "rPodLil1.1_Chr5	95333196" intSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr5	95333196	.	T	A
grep -i "rPodLil1.1_Chr15	33045589" intSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr15	33045589	.	C	T
grep -i "rPodLil1.1_ChrZ	104236" intSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_ChrZ	104236	.	C	G	
grep -i "rPodLil1.1_Chr8	44444931" intSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr8	44444931	.	A	G

#Extsamples
grep -i "rPodLil1.1_Chr6	954289" extSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr6	954289	.	T	C
grep -i "rPodLil1.1_Chr2	59727566" extSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr2	59727566	.	G	A
grep -i "rPodLil1.1_Chr1	115922971" extSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr1	115922971	.	T	G
grep -i "rPodLil1.1_ChrZ	37050411" extSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_ChrZ	37050411	.	T	C
grep -i "rPodLil1.1_Chr11	1787566" extSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr11	1787566	.	A	G
grep -i "rPodLil1.1_Chr10	50471692" extSample.plilfordi_filter_minalle2_maxalle2_MAF005_Q30_minDP10_maxD50_maxMISS075.vcf
#rPodLil1.1_Chr10	50471692	.	T	C
